import { Sparkles, TrendingUp, Users, ShieldCheck } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const dimensions = [
  { label: "Company Fit", value: 92, icon: <ShieldCheck className="h-4 w-4" />, color: "bg-emerald-500", desc: "Industry, size, and tech stack match your ICP" },
  { label: "Contact Access", value: 78, icon: <Users className="h-4 w-4" />, color: "bg-blue-500", desc: "Key decision-makers identified with verified emails" },
  { label: "Opportunity Quality", value: 85, icon: <TrendingUp className="h-4 w-4" />, color: "bg-purple-500", desc: "Strong buying signals from recent activity" },
  { label: "Competitive Position", value: 68, icon: <Sparkles className="h-4 w-4" />, color: "bg-amber-500", desc: "Currently evaluating 2 competitors" },
];

export function ProspectScoreTab() {
  return (
    <div className="space-y-4">
      {/* Score breakdown */}
      <Card className="p-5">
        <div className="flex items-center justify-between mb-5">
          <div>
            <h3 className="font-semibold text-slate-900">AI Prospect Score Breakdown</h3>
            <p className="text-sm text-slate-500 mt-0.5">Generated by LeadPro AI · Updated 2 hours ago</p>
          </div>
          <Badge variant="purple"><Sparkles className="h-3 w-3" /> AI Generated</Badge>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {dimensions.map((d) => (
            <div key={d.label} className="p-4 border border-slate-100 rounded-lg">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <div className={`h-7 w-7 rounded-md text-white flex items-center justify-center ${d.color}`}>{d.icon}</div>
                  <span className="font-medium text-slate-900">{d.label}</span>
                </div>
                <span className="font-bold text-slate-900">{d.value}<span className="text-sm text-slate-400">/100</span></span>
              </div>
              <div className="h-2 bg-slate-100 rounded-full overflow-hidden mb-2">
                <div className={`h-full rounded-full ${d.color}`} style={{ width: `${d.value}%` }} />
              </div>
              <p className="text-xs text-slate-500">{d.desc}</p>
            </div>
          ))}
        </div>
      </Card>

      {/* AI Insights */}
      <Card className="p-5 bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-100">
        <div className="flex items-start gap-3">
          <div className="h-9 w-9 rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600 flex items-center justify-center flex-shrink-0">
            <Sparkles className="h-4 w-4 text-white" />
          </div>
          <div className="flex-1">
            <h3 className="font-semibold text-slate-900 mb-2">AI Insights</h3>
            <p className="text-sm text-slate-700 leading-relaxed mb-3">
              This prospect shows <strong>high purchase intent</strong>. They&apos;ve visited the pricing page twice in 7 days, downloaded the SAP AI guide, and attended a webinar. Their company recently raised Series B funding ($45M), suggesting budget availability.
            </p>
            <div className="grid grid-cols-2 gap-3">
              <div className="bg-white rounded-lg p-3">
                <p className="text-xs text-slate-500 mb-1">Outreach Readiness</p>
                <div className="flex items-center gap-2">
                  <span className="font-bold text-emerald-600">High</span>
                  <span className="h-1.5 w-12 bg-emerald-500 rounded-full" />
                </div>
              </div>
              <div className="bg-white rounded-lg p-3">
                <p className="text-xs text-slate-500 mb-1">Expected Sales Cycle</p>
                <span className="font-bold text-slate-900">30–45 days</span>
              </div>
            </div>
          </div>
        </div>
      </Card>

      {/* Qualification summary */}
      <Card className="p-5">
        <h3 className="font-semibold text-slate-900 mb-3">Qualification Summary</h3>
        <ul className="space-y-2 text-sm">
          {[
            { label: "Budget", status: "Confirmed", variant: "success" as const },
            { label: "Authority", status: "Decision maker identified", variant: "success" as const },
            { label: "Need", status: "Active pain point", variant: "success" as const },
            { label: "Timeline", status: "Within 60 days", variant: "warning" as const },
          ].map((q) => (
            <li key={q.label} className="flex items-center justify-between py-2 border-b border-slate-100 last:border-0">
              <span className="text-slate-600">{q.label}</span>
              <Badge variant={q.variant}>{q.status}</Badge>
            </li>
          ))}
        </ul>
      </Card>
    </div>
  );
}
